project:
  type: website

website:
  title: "analytics.tesselle"

  site-url: https://analytics.huma-num.fr/tesselle/home/
  repo-url: https://github.com/tesselle/analytics
  repo-actions: [edit, issue]

  favicon: /images/icons/favicon.ico
  image: /images/card.png

  search: false
  navbar:
    pinned: true
    right:
      - icon: house
        text: Homepage
        href: "https://www.tesselle.org"
      - icon: github
        text: Github
        href: https://github.com/tesselle/

  page-footer:
    center: |
      <a href="https://www.u-bordeaux-montainge.fr"><img src="https://www.tesselle.org/images/logo-ubm.svg" class="logo-institution" /></a><a href="https://www.cnrs.fr"><img src="https://www.tesselle.org/images/logo-cnrs.svg" class="logo-institution" /></a>
      <br>The tesselle project is supported by <a href="https://www.archeosciences-bordeaux.fr/" target="_blank">Archéosciences Bordeaux</a>, the <a href="https://mshs.univ-toulouse.fr/" target="_blank"><abbr title="Centre de Recherche et d'Études pour l'Art Préhistorique">CREAP</abbr></a> and the <a href="https://www.huma-num.fr/" target="_blank"><abbr title="Très Grande Infrastructure de Recherche">TGIR</abbr> Huma-Num</a>.

format:
  html:
    theme:
      - default
      - custom.scss
